import { ArrowRight, Check, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';

export function LandingPage() {
  return (
    <main className="min-h-screen bg-[#f5f5f2] text-[#111]">
      <nav className="max-w-6xl mx-auto px-5 sm:px-8 py-6 flex items-center justify-between">
        <Link to="/" className="flex items-center gap-2.5"><span className="w-9 h-9 rounded-xl bg-[#111] text-white flex items-center justify-center font-bold">O</span><span className="font-semibold tracking-tight">Outbound</span></Link>
        <div className="flex items-center gap-3"><Link to="/signin" className="text-sm font-medium text-[#686868] hover:text-[#111]">Sign in</Link><Link to="/signup" className="px-4 py-2.5 rounded-xl bg-[#3157FF] text-white text-sm font-semibold">Get started</Link></div>
      </nav>
      <section className="max-w-6xl mx-auto px-5 sm:px-8 pt-16 sm:pt-24 pb-20 grid lg:grid-cols-[0.9fr_1.1fr] gap-14 items-center">
        <div><div className="inline-flex items-center gap-2 rounded-full border border-black/10 bg-white/70 px-3 py-1.5 text-xs font-medium text-[#686868]"><Sparkles className="w-3.5 h-3.5 text-[#3157FF]" />Focused outbound intelligence</div><h1 className="text-5xl sm:text-7xl font-semibold tracking-[-0.07em] leading-[0.95] mt-6">Turn the right prospects into real conversations.</h1><p className="text-lg text-[#686868] leading-relaxed mt-7 max-w-xl">Outbound helps you discover high-fit companies, understand what matters to them, and create thoughtful outreach from one focused workspace.</p><div className="flex flex-wrap items-center gap-3 mt-8"><Link to="/signup" className="px-5 py-3 rounded-xl bg-[#3157FF] text-white text-sm font-semibold flex items-center gap-2">Create your workspace <ArrowRight className="w-4 h-4" /></Link><Link to="/signin" className="px-5 py-3 rounded-xl border border-black/10 bg-white text-sm font-semibold">Sign in</Link></div><div className="flex flex-wrap gap-x-5 gap-y-2 mt-8 text-xs text-[#686868]"><span className="flex items-center gap-1.5"><Check className="w-3.5 h-3.5 text-emerald-600" />Review before sending</span><span className="flex items-center gap-1.5"><Check className="w-3.5 h-3.5 text-emerald-600" />Your workspace stays yours</span></div></div>
        <div className="rounded-[28px] border border-black/10 bg-white p-3 shadow-[0_24px_80px_rgba(17,17,17,0.12)]"><div className="rounded-[22px] bg-[#f7f7f5] border border-black/[0.06] p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="text-xs text-[#949494]">Overview</p><h2 className="text-2xl font-semibold tracking-tight mt-1">Good day, your next lead is here.</h2></div><span className="w-9 h-9 rounded-xl bg-[#111] text-white flex items-center justify-center font-bold">O</span></div><div className="grid grid-cols-3 gap-3 mt-7"><div className="bg-white rounded-2xl p-4 border border-black/[0.06]"><p className="text-[11px] text-[#949494]">High-fit leads</p><p className="text-2xl font-semibold mt-2">128</p></div><div className="bg-white rounded-2xl p-4 border border-black/[0.06]"><p className="text-[11px] text-[#949494]">Research ready</p><p className="text-2xl font-semibold mt-2">64</p></div><div className="bg-white rounded-2xl p-4 border border-black/[0.06]"><p className="text-[11px] text-[#949494]">Replies</p><p className="text-2xl font-semibold mt-2">18</p></div></div><div className="mt-4 bg-white rounded-2xl border border-black/[0.06] p-4 space-y-3"><div className="flex justify-between text-xs"><span className="font-semibold">Research queue</span><span className="text-[#3157FF]">View all</span></div>{['Northline Kitchens','Apex Roofing Systems','Evergreen Mechanical'].map((name, i) => <div key={name} className="flex items-center justify-between py-2 border-t border-black/[0.06]"><span className="text-sm">{name}</span><span className="text-xs text-emerald-700">{[94, 91, 88][i]} fit score</span></div>)}</div></div></div>
      </section>
    </main>
  );
}
